### ISSUE TITLE
Step 5 - Deploy the XOM via Blockchain - fails

### ISSUE THREAD

**Issue by rs2015** [ODMDev/sample-blockchain-vehicle-lifecycle#23]
Step 5/ Deploy the XOM via Blockchain (provided the XOM has been generated by Rule Designer before)
* go to vehicle-lifecycle-cli
* the first time you need to run npm install to set-up the client application
* npm run deployXom

Above fails with following message
info: [Vehicle Lifecycle] Vehicle Lifecycle application
error: [Vehicle Lifecycle] Error: Error trying to ping. Error: Composer runtime (0.12.0) is not compatible with client (0.11.3)
Command failed.

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/rpatel/.nvm/versions/node/v6.11.1/bin/node" "/Users/rpatel/.nvm/versions/node/v6.11.1/bin/npm" "run" "deployXom"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vehicle-lifecycle-cli@1.0.0 deployXom: `node cli.js deployXom ../vehicle-lifecycle-decision-service/output/vehicle-lifecycle-xom.zip 1.0`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vehicle-lifecycle-cli@1.0.0 deployXom script 'node cli.js deployXom ../vehicle-lifecycle-decision-service/output/vehicle-lifecycle-xom.zip 1.0'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vehicle-lifecycle-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node cli.js deployXom ../vehicle-lifecycle-decision-service/output/vehicle-lifecycle-xom.zip 1.0
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vehicle-lifecycle-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vehicle-lifecycle-cli
npm ERR! There is likely additional logging output above.

**Comment by stephane-mery** [comment]
you need to change the package.json file to update the version of Composer you are using and need to run npm install to reflect the new version of Composer CLI used in this project

**Comment by rs2015** [comment]
![screen shot 2017-10-04 at 12 18 15 pm](https://user-images.githubusercontent.com/5671385/31191784-ed4eb144-a904-11e7-9786-720d1e7f3272.png)
![screen shot 2017-10-04 at 12 17 49 pm](https://user-images.githubusercontent.com/5671385/31191791-f07d3d90-a904-11e7-8f3c-8b234a20d0c1.png)

Hi Stephane, changed package.json and executed “nom install”.

Now I get error - error: [Vehicle Lifecycle] Error: Failed to load connector module "composer-connector-hlfv1" for connection profile "hlfv1". Error: Cannot find module 'grpc'
Command failed.


Please see attached two screenshots.

Thanks

**Comment by stephane-mery** [comment]
looks like a composer installation issue. Can you try composer -v? can you check possible resolution  for https://github.com/hyperledger/composer/issues/1531? 

Just committed instructions in Tips.txt to upgrade composer. Can try to update to Composer 0.13.0?

**Comment by rs2015** [comment]
Hi Stephanie,

This is resolved. I updated node to 6.11.4 and switched npm from 3.10.10 to 5.4.2.

Also re-installed composer tooling
npm install -g composer-cli
npm install -g generator-hyperledger-composer
npm install -g composer-rest-server
npm install -g yo
npm install -g composer-playground

Finally, demo working end-to-end.

Thank you for all your help.

Raj--
