### ISSUE TITLE
Data not being sent from Blockchain to ODM Service

### ISSUE THREAD

**Issue by anushaath** [ODMDev/sample-blockchain-vehicle-lifecycle#25]
The privateVehicleTransfer transaction calls the ODM service along with the data of dsCallObject. But once the block of code is executed, it always goes to the catch block. 
![screenshot from 2018-04-11 12-23-15](https://user-images.githubusercontent.com/11595241/38600840-3ad41b4e-3d83-11e8-8c01-7d99882f6eac.png)

I tested the ODM url using Postman with the same payload, and it gives me the right output. 

I think the `return post(url, dsCallObject, )` is not sending the JSON object and hence it always redirects to the catch block.

**Comment by anushaath** [comment]
Also the order is placed by a PrivateOwner participant. But the transfer of vehicle transaction takes a participant Person as input.

`transaction PrivateVehicleTransfer extends VehicleTransaction {
  --> Person seller
  --> Person buyer
  o String specialNotes optional
}
`
https://github.com/ODMDev/sample-blockchain-vehicle-lifecycle/blob/711307ab38facbdb4320e361cdc9699ba45b64fe/vehicle-lifecycle/models/vda.cto#L122

So actually when you submit a PrivateVehicleTransfer transaction, the Hyperledger Fabric docker image log file shows an error of missing Identity.

**Comment by stephane-mery** [comment]
I've just updated the sample to run on Fabric 1.1 and Composer 0.19.1. I've made some test on my environment and it seems to work correctly. Can you try again?

**Comment by stephane-mery** [comment]
Didn't look at the identity issue. We will tackle that in a further major version of this sample, which is not planned at this point.

**Comment by anushaath** [comment]
Yes, Thanks Stephane. I also found that the reason it didn't work is because I had deleted some fields like deathDetails from the blockchain code, but did not update the java files in ODM. As such, this issue is resolved.
